spring.application.name=nutrichef-backend
server.port=8081

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/nutrichef
spring.datasource.username=postgres
spring.datasource.password=Juanpablobd05#
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate — update crea columnas nuevas sin borrar datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Deshabilitar Open-Session-in-View para evitar lazy-loading issues
spring.jpa.open-in-view=false
