spring.application.name=nutrichef-backend
server.port=8081

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/nutrichef
spring.datasource.username=postgres
spring.datasource.password=Juanpablobd05#
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
# update: schema is created and updated automatically without dropping tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
